services:
  admin-service:
    image: g3global/admin-service@sha256:c38f9d6e68fae2e7646fdcc5f081047ceba8392d0e3658fb1dd6a74a8a9e6064
  admin-ui:
    image: g3global/admin-ui@sha256:15290e38c843e751fa2f51296945606375f862ad13051f294ffc1807a5ee6329
  api-gateway:
    image: g3global/api-gateway@sha256:9c2a990a4e62982cd7eb7f483ef198278d7339975e48fb2c1a0fe772ef0edbdd
  auth-service:
    image: g3global/auth-service@sha256:58b3aae551aed02fdc29ba0a04d763999da0ea5ef48189c71e11ce5db03b8a41
  chatting-service:
    image: g3global/chatting-service@sha256:412832df16cb87386527b0a0f1c7c0c7123413b6c84eae651c964ba56b9abf0b
  kafka:
    image: confluentinc/cp-kafka@sha256:187dac6627e7906c350f5f8c982f80ce735ff1a0e571a20de6000a309a12ce63
  kafka-service:
    image: g3global/kafka-service@sha256:f153a6c0a79a50b676c72ed86f9121c56245cd0e87f4a3c7de5f979c825f1551
  kafka-setup:
    image: confluentinc/cp-kafka@sha256:187dac6627e7906c350f5f8c982f80ce735ff1a0e571a20de6000a309a12ce63
  logger-service:
    image: g3global/logger-service@sha256:d8fc5f1c6da088a6b6cf0a944bf841a6523eb697e2cbf291b4fbc421144a5179
  nginx:
    image: nginx@sha256:42a516af16b852e33b7682d5ef8acbd5d13fe08fecadc7ed98605ba5e3b26ab8
  order-service:
    image: g3global/order-service@sha256:45193e44a1c701d6bca207d4509f931ecb9cb658289690a2e6eb32c80687fe73
  product-service:
    image: g3global/product-service@sha256:872e017eaa4484ce5a3993499aa5d9660e0f2aed8e404b537747ac846055d313
  recommendation-service:
    image: g3global/recommendation-service@sha256:a4b9ef765b261a2484ea01b255afeae3ed9a63de6b6f3e9531b7b4c26e5ca643
  seller-service:
    image: g3global/seller-service@sha256:fdb5ec94883841b06a63dc1add04c13c621571050495986f29755fc44245514f
  seller-ui:
    image: g3global/seller-ui@sha256:67d4b550910cf24bef9b391647ebc4b0b1d60b83c7fa20a67cfb26bf36d41edf
  user-ui:
    image: g3global/user-ui@sha256:d88e58c5f15ee6998cc68b5b0e8d501c1ad191b5a7ffe219d695af19027a6e32
  zookeeper:
    image: confluentinc/cp-zookeeper@sha256:90631f224b4397ecfb4e824e43d93e0e42656841c6d55ef635c49df3975260ae
